{
    "name": "WaterLevelControl",
    "version": "0.0.1",
    "icon": "fab fa-battle-net",
    "category": "undefined",
    "author": "LazzaAU",
    "maintainers": [],
    "desc": "Monitor and control water level of your tanks",
    "aliceMinVersion": "1.0.0-b1",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "asrArbitraryCapture": true
    }
}